package ed.back_snekhome.enums;

public enum LogType {
    DELETE_POST, BAN_USER, GRANT_ROLE, REVOKE_ROLE, ACCEPT_JOIN_REQUEST, JOIN_BY_INVITE,
    NEW_COMMUNITY_TITLE, NEW_GROUPNAME, NEW_DESCRIPTION, NEW_IMAGE, DELETE_IMAGE,
    RULE_ANON_POSTS, RULE_CLOSED_COMMUNITY, RULE_INVITE_USERS,
    NEW_CITIZEN_REQUIREMENTS_DAYS, NEW_CITIZEN_REQUIREMENTS_RATING, NEW_ELECTIONS_PERIOD
}
