package ed.back_snekhome.enums;

public enum LogType {
    DELETE_POST, BAN_USER, GRANT_ROLE, NEW_COMMUNITY_TITLE, NEW_GROUPNAME, NEW_DESCRIPTION,
    ACCEPT_JOIN_REQUEST, JOIN_BY_INVITE, RULE_ANON_POSTS, RULE_CLOSED_COMMUNITY, RULE_INVITE_USERS,
    NEW_CITIZEN_REQUIREMENTS
}
